### ISSUE TITLE
卷一第二款某處疑似不通

### ISSUE THREAD

**Issue by SiobaraIsara** [NSKernel/IntroductionToCalculus#5]
卷一第二款中，有一句「如解其方程式爲……則戌變爲天之陰函數」（對應於源代碼 [此行](https://github.com/NSKernel/IntroductionToCalculus/blob/74fa28db4d88587f219062809d294c9b91b34ab0/Chapters/%E5%BE%AE%E7%A9%8D%E6%BA%AF%E6%BA%90%E5%8D%B7%E4%B8%80.tex#L33)），讀來似有不通：按其含義，戌在解出方程之前就已是天之陰函數，此處或應是「變爲天之**陽**函數」。

如上是在並無源文本的情況下作的猜測。值此也提一問，即校訂所依據的源文本（大概應該叫「底本」？我不懂校讎學，不確定用得對不對）來自何處，（如果可能的話）應該如何獲取。

多謝。

**Comment by NSKernel** [comment]
校訂底本爲西安交通大學圖書館藏江南機器製造總局同治初版，您可以在CADAL上找到掃描件（http://www.cadal.zju.edu.cn/book/04200423/1/search@query=微積溯源,type=all,tag=,publisher=。需註冊帳戶，然而註冊過程十分簡單且不太需要什麼特別的東西）。由於印刷問題因此採用了廣島大學藏的同版（http://dc.lib.hiroshima-u.ac.jp/text/detail/121220141210171122。缺序，且metadata不正確）做參校本。

您所說的問題我重新校對了上述兩個版本，原文均做「陰函數」。然而您所說的確實有道理，因爲解開方程後戌的確當爲天之陽函數，因而我們認爲初版卽存在問題。於是問題變爲了是刻板出問題還是翻譯時就搞錯了，甚至是原文存在問題。原文出典爲第八版大英百科全書中William Wallace所撰流數（Fluxions）一章（約在1852年付梓），您可以在https://babel.hathitrust.org/cgi/pt?id=uc1.c2755772;view=1up;seq=692找到原文，原文在第680頁，我引其原文如下："... u is now an explicit function of x"，也就是說William Wallace認爲u（也就是戌）是x（也就是天）的陽函數（explicit function），所以原文正確。此時考慮刻板出錯和翻譯出錯。

在校讎學中，學術界的看法爲：如果確定是刻板出錯，則當改；如果是作者（譯者）寫錯，則不改。其核心在於還原作者的「原文」。然而對於這種不知其錯出於哪裡的情況，學界尚存疑義。有部分觀點認爲這種情況保留最早版本的文字，也有部分觀點認爲如果已經發現明顯錯誤了則當改，但當出校（也就是寫校勘記）。我的恩師武秀成教授選擇後者，因此我也因其道認爲您說的應當修改是有一定道理的。

然而我畢竟是計算機系的學生，在文學院甚至不是修課程而只是參與項目，因此算半個業餘。這裏的問題與我之前做的其他修訂工程的區別在於之前那些工程幾乎找不到初版，因此都是按照後人翻刻的本子來做的。而這個版本本來就是初版，那麼這種情況我其實不是很拿得準這個字改還是不改。我計畫在目前先原文中留下一個註釋，下學期回學校後請教我的老師來討論出一個比較好的結論，您覺得如何？

**Comment by SiobaraIsara** [comment]
感謝如此認眞的攷證與回覆，辛苦了。

我作爲此前從未接觸過校讎學的、完全的外行，其實沒有太多可以說的（也並未說過「應當修改」或否😂）。僅基於上述幾段詳盡的說明，我贊同目前先這樣做。
